services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 15432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=echo_example

volumes:
  db-store:
